import 'package:flutter/material.dart';
// import 'package:http/http.dart' as http;
import '../models/news.dart';

class ProductProvider extends ChangeNotifier {
  bool isLoading = false;
  // ignore: prefer_final_fields
  List<Product> _products = [
    Product(
      id: '0',
      title:
          'KPK Tangkap Pejabat Kemenkes Terkait Kasus Suap Proyek Pengadaan Alat Medis',
      description:
          'Komisi Pemberantasan Korupsi (KPK) kembali menunjukkan tajinya dalam menindak tegas kasus korupsi di Indonesia. Pada Selasa (5/4/2023), KPK melakukan operasi tangkap tangan (OTT) terhadap sejumlah pejabat di Kementerian Kesehatan terkait kasus dugaan suap dalam proyek pengadaan alat medis. Kasus ini menjadi sorotan publik mengingat pentingnya alat medis dalam penanganan pandemi Covid-19 yang masih terjadi di Indonesia.\n\n Berdasarkan informasi dari KPK, dalam operasi tersebut terdapat beberapa pejabat yang diamankan dan disita sejumlah barang bukti, termasuk uang tunai senilai ratusan juta rupiah. Pejabat-pejabat tersebut diduga telah menerima suap dari pihak-pihak yang tertarik untuk memenangkan proyek pengadaan alat medis di Kementerian Kesehatan. Selain itu, KPK juga melakukan penggeledahan di beberapa lokasi, termasuk kantor dan rumah para pejabat yang terlibat.\n\n Menanggapi kasus ini, Ketua KPK, Firli Bahuri, menegaskan bahwa KPK tidak akan pernah berhenti untuk memberantas korupsi, terlebih di sektor kesehatan yang menjadi prioritas nasional dalam mengatasi pandemi Covid-19. Ia juga menekankan bahwa KPK akan menindak tegas pelaku korupsi tanpa pandang bulu, termasuk jika pelakunya adalah pejabat publik atau pihak swasta.\n\n Kasus suap dalam proyek pengadaan alat medis di Kementerian Kesehatan bukanlah hal baru di Indonesia. Sebelumnya, KPK juga telah menangani beberapa kasus serupa di lembaga kesehatan lainnya. Namun, kasus ini menunjukkan bahwa masih ada pejabat publik yang berani melakukan tindakan korupsi meski negara sedang berjuang untuk mengatasi pandemi global yang mengancam kesehatan dan ekonomi masyarakat.\n\n Di sisi lain, kasus ini juga menjadi momentum bagi pemerintah dan masyarakat untuk terus mendukung upaya pemberantasan korupsi di Indonesia. Selain itu, lembaga-lembaga pemerintah juga perlu melakukan pembenahan sistem pengadaan barang dan jasa yang lebih transparan dan akuntabel agar dapat mencegah terjadinya kasus-kasus korupsi di masa depan.\n\n Dalam kesimpulannya, kasus suap proyek pengadaan alat medis di Kementerian Kesehatan yang diungkap oleh KPK menjadi bukti nyata bahwa korupsi masih menjadi masalah serius di Indonesia. Oleh karena itu, peran masyarakat dan lembaga-lembaga pemerintah dalam memberantas korupsi harus terus ditingkatkan. Dengan begitu, Indonesia dapat menjadi negara yang lebih baik dan bersih dari praktik korupsi yang merugikan rakyat.',
      images: 'assets/images/img1.jpeg',
    ),
    Product(
      id: '1',
      title: 'Pertamina Naikkan Harga Bahan Bakar Minyak Mulai Bulan Ini',
      description:
          'Pertamina sebagai perusahaan milik negara yang bertanggung jawab atas pasokan bahan bakar minyak di Indonesia, mengumumkan kenaikan harga bahan bakar mulai bulan ini. Kenaikan ini merupakan dampak dari kenaikan harga minyak mentah dunia yang terjadi beberapa waktu lalu. Kenaikan harga ini tentu saja berdampak pada pengguna kendaraan dan sektor bisnis di Indonesia.\n\n Dalam pengumuman resminya, Pertamina mengatakan bahwa harga bahan bakar jenis Premium akan naik sebesar Rp. 500 per liter, dari Rp. 6.450 per liter menjadi Rp. 6.950 per liter. Sementara itu, harga bahan bakar jenis Pertalite akan naik sebesar Rp. 400 per liter, dari Rp. 7.650 per liter menjadi Rp. 8.050 per liter. Selain itu, harga bahan bakar jenis Pertamax dan Pertamax Turbo juga akan mengalami kenaikan sebesar Rp. 400 per liter.\n\n Kenaikan harga bahan bakar minyak ini tentu saja menjadi kabar yang kurang baik bagi masyarakat dan sektor bisnis di Indonesia. Sejak pandemi Covid-19 melanda Indonesia pada awal 2020, sektor bisnis dan perekonomian Indonesia masih dalam kondisi yang belum stabil. Kenaikan harga bahan bakar minyak akan memberikan dampak langsung pada biaya operasional sektor transportasi dan sektor bisnis lainnya.\n\n Namun, Pertamina juga menegaskan bahwa kenaikan harga bahan bakar minyak ini merupakan keputusan yang sulit yang harus diambil demi menjaga keseimbangan keuangan perusahaan dan memastikan pasokan bahan bakar tetap terjaga di tengah situasi harga minyak mentah dunia yang tidak stabil.\n\n Untuk mengatasi dampak kenaikan harga bahan bakar minyak ini, pemerintah dan sektor bisnis di Indonesia harus bergerak cepat untuk menyesuaikan biaya operasional dan mencari cara-cara alternatif yang lebih efisien dalam penggunaan bahan bakar. Di sisi lain, pemerintah juga perlu memberikan dukungan yang lebih besar bagi sektor bisnis dan masyarakat yang terdampak langsung oleh kenaikan harga bahan bakar minyak.\n\n Dalam kesimpulannya, kenaikan harga bahan bakar minyak yang diumumkan oleh Pertamina akan memberikan dampak langsung pada biaya operasional sektor transportasi dan sektor bisnis lainnya di Indonesia. Namun, keputusan ini diambil demi menjaga keseimbangan keuangan perusahaan dan memastikan pasokan bahan bakar tetap terjaga. Pemerintah dan sektor bisnis perlu bergerak cepat dalam mencari cara-cara alternatif yang lebih efisien dalam penggunaan bahan bakar serta memberikan dukungan yang lebih besar bagi sektor bisnis dan masyarakat yang terdampak langsung oleh kenaikan harga bahan bakar minyak ini.',
      images: 'assets/images/img2.jpeg',
    ),
    Product(
      id: '3',
      title: 'Gempa Magnitudo 6,0 Guncang Aceh, Belum Ada Laporan Korban',
      description:
          'Gempa bumi dengan magnitudo 6,0 mengguncang wilayah Aceh pada Senin (5/4) pagi. Menurut informasi dari Badan Meteorologi, Klimatologi, dan Geofisika (BMKG), gempa terjadi pada pukul 05.22 WIB dengan pusat gempa berada di laut sebelah barat daya Kabupaten Simeulue, Aceh.\n\n Hingga saat ini, belum ada laporan korban jiwa atau kerusakan bangunan akibat gempa ini. Namun, beberapa warga yang merasakan getaran kuat dari gempa tersebut panik dan berhamburan keluar rumah. BMKG juga mengeluarkan peringatan dini tsunami untuk wilayah pesisir Aceh, namun peringatan tersebut kemudian dicabut setelah beberapa saat.\n\n Pemerintah Aceh dan BMKG terus memantau situasi pasca-gempa dan meminta masyarakat di wilayah tersebut untuk tetap waspada dan mengikuti instruksi dari pihak berwenang. Sementara itu, tim gabungan dari Basarnas, TNI, Polri, dan BPBD Aceh telah bergerak ke lokasi gempa untuk melakukan pemantauan dan membantu apabila ada korban atau kerusakan yang terjadi.\n\n Gempa bumi merupakan bencana alam yang tidak dapat diprediksi dengan pasti. Oleh karena itu, penting bagi masyarakat untuk terus memperhatikan peringatan dini yang dikeluarkan oleh BMKG dan pihak berwenang saat terjadi gempa. Masyarakat juga diharapkan untuk mengikuti instruksi-evakuasi dan tidak panik saat terjadi gempa.\n\n Aceh merupakan daerah yang sering mengalami gempa bumi karena berada di jalur lempeng tektonik yang aktif. Pemerintah dan masyarakat di wilayah tersebut perlu terus memperkuat kesiapsiagaan dan tindakan mitigasi bencana untuk mengurangi dampak dari gempa bumi dan bencana alam lainnya.\n\n Dalam kesimpulannya, gempa bumi magnitudo 6,0 yang terjadi di Aceh pada Senin (5/4) pagi membuat warga setempat panik dan berhamburan keluar rumah. Hingga saat ini belum ada laporan korban jiwa atau kerusakan bangunan akibat gempa ini. Namun, penting bagi masyarakat untuk tetap waspada dan mengikuti instruksi dari pihak berwenang saat terjadi gempa. Pemerintah dan masyarakat di wilayah tersebut perlu terus memperkuat kesiapsiagaan dan tindakan mitigasi bencana alam untuk mengurangi dampak dari gempa bumi dan bencana alam lainnya.',
      images: 'assets/images/img3.jpeg',
    ),
    Product(
      id: '4',
      title:
          'Kasus Covid-19 di Indonesia Terus Menurun, Pemerintah longgarkan PPKM',
      description:
          'Indonesia telah melihat penurunan jumlah kasus Covid-19 selama beberapa minggu terakhir, dan hal ini memicu Pemerintah untuk melonggarkan pembatasan PPKM (Pemberlakuan Pembatasan Kegiatan Masyarakat) di sejumlah wilayah. Pada akhir Januari 2022, Pemerintah mengumumkan bahwa PPKM akan diperpanjang sampai akhir Februari, namun beberapa daerah dengan kasus Covid-19 yang rendah akan diberikan kelonggaran dalam PPKM.\n\n Meskipun angka kasus Covid-19 di Indonesia terus menurun, Pemerintah masih mewanti-wanti masyarakat untuk tetap waspada dan disiplin dalam menerapkan protokol kesehatan. Beberapa langkah penting yang harus diikuti termasuk menjaga jarak sosial, menghindari kerumunan, memakai masker, mencuci tangan dengan sabun secara rutin, serta menjaga kebersihan lingkungan.\n\n Langkah-langkah yang diperketat selama beberapa bulan terakhir, termasuk pembatasan perjalanan dan kegiatan sosial, juga telah membantu dalam menekan penyebaran virus di Indonesia. Meskipun PPKM telah dilonggarkan, penting bagi masyarakat untuk tetap memperhatikan kondisi kesehatan mereka dan tetap waspada terhadap penyebaran virus.\n\n Selain itu, vaksinasi juga dianggap sebagai kunci penting dalam mengatasi pandemi Covid-19. Pemerintah Indonesia telah melakukan vaksinasi massal dan terus memperluas cakupan vaksinasi untuk masyarakat. Selain itu, Pemerintah juga mendorong masyarakat untuk mematuhi aturan-aturan kesehatan seperti menjaga jarak sosial, memakai masker, dan mencuci tangan secara rutin.\n\n Kondisi pandemi Covid-19 di Indonesia dan dunia terus berubah dan memerlukan perhatian yang serius. Oleh karena itu, penting bagi masyarakat untuk terus memperhatikan informasi terbaru tentang situasi Covid-19 dan tetap disiplin dalam menerapkan protokol kesehatan. Dengan demikian, diharapkan pandemi ini dapat segera diatasi dan kehidupan kembali normal seperti sedia kala.',
      images: 'assets/images/img4.jpeg',
    ),
    Product(
      id: '5',
      title:
          'TikTok Buka Peluang Bagi Creator untuk Monetisasi Video Melalui Donasi',
      description:
          'TikTok, platform media sosial populer yang terkenal karena video pendeknya, kini memberikan kesempatan bagi penggunanya untuk mendapatkan uang dari video yang diunggah melalui program donasi baru yang diluncurkan oleh perusahaan. Program tersebut akan memungkinkan para pengguna TikTok yang telah memenuhi syarat untuk menerima sumbangan dari penonton dalam bentuk koin TikTok. Koin-koin tersebut kemudian dapat ditukarkan dengan uang.\n\n Dengan memungkinkan pengguna untuk mendapatkan penghasilan melalui donasi, TikTok berharap dapat menarik lebih banyak konten kreatif dari para pembuat video di platform mereka. Program donasi ini terutama ditujukan untuk pembuat konten yang telah membangun basis penggemar yang besar dan aktif di TikTok.\n\n Untuk memenuhi syarat, para pembuat konten harus memenuhi beberapa kriteria, seperti harus memiliki setidaknya 18 tahun atau lebih, memiliki setidaknya 100 ribu pengikut di TikTok, dan telah menghasilkan setidaknya 100 ribu tampilan video dalam 30 hari terakhir. Setelah memenuhi syarat, pembuat konten dapat mengaktifkan fitur donasi pada video mereka dan menampilkan jumlah koin yang diterima dari penonton.\n\n Program donasi TikTok telah diluncurkan di beberapa negara dan telah memberikan hasil yang menggembirakan. Beberapa pengguna TikTok telah berhasil menghasilkan uang dari fitur donasi tersebut, bahkan ada yang menghasilkan ribuan dolar dalam sehari. Namun, kesuksesan ini tergantung pada kreativitas dan popularitas pembuat konten, serta kemampuan mereka dalam membangun hubungan yang kuat dengan penggemar mereka.\n\n TikTok telah berkembang pesat selama beberapa tahun terakhir dan menjadi salah satu platform media sosial paling populer di dunia, terutama di kalangan pengguna muda. Program donasi ini menunjukkan komitmen perusahaan untuk membantu para pembuat konten TikTok dalam memonetisasi video mereka, sekaligus meningkatkan kualitas konten di platform tersebut.\n\n Kendati demikian, perlu diingat bahwa pengguna TikTok juga harus tetap memperhatikan hak cipta dan aturan-aturan yang berlaku di platform tersebut. TikTok memiliki kebijakan ketat terkait konten yang melanggar hak cipta, serta konten yang mengandung kekerasan, kebencian, atau tindakan merugikan. Oleh karena itu, penting bagi pengguna TikTok untuk mematuhi aturan dan menjaga kualitas konten mereka.',
      images: 'assets/images/img5.jpeg',
    ),
    Product(
      id: '6',
      title:
          'Tesla Luncurkan Mobil Listrik Terbaru dengan Fitur Kecerdasan Buatan yang Lebih Unggul',
      description:
          'Tesla, perusahaan mobil listrik terkemuka, baru saja meluncurkan model terbaru mereka, yaitu Model Y. Mobil listrik ini dilengkapi dengan fitur kecerdasan buatan yang lebih unggul dibandingkan dengan model-model sebelumnya.\n\n Fitur utama pada Model Y adalah kemampuan untuk mengemudi semi-otonom, yang memungkinkan mobil untuk melakukan manuver seperti memutar, berganti jalur, dan mengontrol kecepatan di jalan tol dengan sendirinya. Selain itu, mobil ini dilengkapi dengan teknologi kamera dan sensor yang lebih canggih, sehingga dapat memprediksi dan menghindari bahaya di jalan.\n\n Selain fitur keamanan, Model Y juga memiliki beberapa peningkatan pada fitur hiburan dan kenyamanan. Mobil ini memiliki layar sentuh 15 inci dengan sistem infotainment terbaru, serta speaker yang lebih canggih yang menjamin pengalaman audio yang luar biasa.\n\n Dalam hal performa, Model Y juga tidak kalah dengan mobil listrik lainnya. Mobil ini dapat menempuh jarak hingga 326 mil dengan sekali pengisian baterai, dan dapat mencapai kecepatan 60 mil per jam dalam waktu 3,5 detik. Selain itu, Model Y juga dilengkapi dengan suspensi udara adaptif yang dapat menyesuaikan tinggi mobil sesuai dengan kondisi jalan.\n\n Model Y adalah contoh terbaru dari upaya Tesla dalam mendorong penggunaan mobil listrik sebagai kendaraan masa depan yang lebih ramah lingkungan. Dengan fitur-fitur terbaru dan kemampuan kecerdasan buatan yang canggih, Tesla berharap dapat memenuhi permintaan konsumen untuk mobil yang aman, nyaman, dan efisien.\n\n Namun, seperti halnya kendaraan lainnya, Model Y juga memiliki harga yang cukup mahal, yang mungkin tidak terjangkau bagi sebagian orang. Meskipun demikian, Tesla terus mengembangkan teknologi mobil listrik mereka dan berupaya untuk membuatnya lebih terjangkau dan ramah lingkungan.\n\n Dalam waktu dekat, Tesla juga berencana untuk memperluas produksi dan penjualan mobil listrik mereka ke pasar global, termasuk ke Indonesia. Dengan harapan dapat mendorong penggunaan kendaraan listrik di seluruh dunia, Tesla terus berinovasi dan meningkatkan teknologi mobil listrik mereka untuk memberikan pengalaman berkendara yang lebih baik bagi penggunanya. ',
      images: 'assets/images/img6.jpeg',
    ),
  ];
  List<Product> get products => _products;

  Future<void> getProducts() async {
    isLoading = true;
    notifyListeners();

    // final response = await http.get(Uri.parse(
    //     'https://api.escuelajs.co/api/v1/products?offset=1&limit=10'));

    // _products = productFromJson(response.body);
    isLoading = false;
    notifyListeners();
  }
}
